name: flutter_application_2
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  google_fonts: ^6.2.1
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path: ^1.8.0
  provider: ^6.1.2
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.0.17
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Bagian Assets cukup ditulis sekali seperti ini bang
  assets:
    - assets/images/logo.jpeg
    - assets/images/